# This file is created as a demonstration example
# Normally you should use config/settings.yml
# or files config/settings/%{environment}.yml

# Also this file is being loaded in `config/application.rb`
# To make configs available in `config/environments/%{environment}.rb`

# Settings.rails.version
rails:
  version: <%= ENV['RAILS_VERSION'] %>

# Settings.app.env.name
app:
  host: <%= ENV['APP_HOST'] %>

redis:
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>

elastic:
  host: <%= ENV['ELASTIC_HOST'] %>
  port: <%= ENV['ELASTIC_PORT'] %>

seeds:
  admin:
    email: <%= ENV['ADMIN_EMAIL'] %>
    password: <%= ENV['ADMIN_PASSWORD'] %>
