# This file is created as a demonstration example
# Normally you should use config/settings.yml
# or files config/settings/%{environment}.yml

# Also this file is being loaded in `config/application.rb`
# To make configs available in `config/environments/%{environment}.rb`

# Settings.app.rails.version
app:
  rails:
    version: <%= ENV['RAILS_VERSION'] %>

redis:
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>

elastic:
  host: <%= ENV['ELASTIC_HOST'] %>
  port: <%= ENV['ELASTIC_PORT'] %>
