# This file is created as a demonstration example
# Normally you should use config/settings.yml
# or files config/settings/%{environment}.yml

# Also this file is being loaded in `config/application.rb`
# To make configs available in `config/environments/%{environment}.rb`

# Settings.rails.version
rails:
  version: <%= ENV['RAILS_VERSION'] %>

# Settings.app.db.name
db:
  pool:     <%= ENV.fetch('DATABASE_POOL', 5) %>
  host:     <%= ENV.fetch('DATABASE_HOST', 'psql') %>
  user:     <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  name:     <%= ENV.fetch('DATABASE_NAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>

# Settings.app.env.name
app:
  host: <%= ENV['APP_HOST'] %>

redis:
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>

elastic:
  host: <%= ENV['ELASTIC_HOST'] %>
  port: <%= ENV['ELASTIC_PORT'] %>

seeds:
  admin:
    email: <%= ENV['ADMIN_EMAIL'] %>
    password: <%= ENV['ADMIN_PASSWORD'] %>
