defaults: &defaults
  pool: <%= Settings.db.pool %>
  host: <%= Settings.db.host %>
  username: <%= Settings.db.user %>
  database: <%= Settings.db.name %>
  password: <%= Settings.db.password %>

test:
  adapter:  postgresql
  encoding: unicode
  <<: *defaults

development:
  adapter:  postgresql
  encoding: unicode
  <<: *defaults

production:
  adapter:  postgresql
  encoding: unicode
  <<: *defaults
