---
:verbose: true
:logfile: ./log/sidekiq.log
:pidfile: ./tmp/pids/sidekiq.pid

:concurrency: 3

development:
  :logfile: ./log/sidekiq.log
  :pidfile: ./tmp/pids/sidekiq.pid

staging:
  :concurrency: 2

production:
  :concurrency: 2

:queues:
  - critical
  - default
  - low
